[project]
name = "pixel-factory-images"
version = "0.1.0"
description = "Fetch Pixel factory image metadata"
readme = "README.md"
requires-python = ">=3.0"
dependencies = [
    "beautifulsoup4>=4.9.3",
    "requests>=2.25.1",
]
